# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth’
pod 'Firebase/Database’

target 'Shopping' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Shopping
  target 'ShoppingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Shopping-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Shopping-tvOS

  target 'Shopping-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
